# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='card',
            name='double_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='double_patch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='patch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='rookie_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.CharField(default='Patriots', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='year',
            field=models.IntegerField(default=2015),
        ),
    ]
