# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 12:37
from __future__ import unicode_literals

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20160523_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cards.models.get_image_path),
        ),
    ]
