# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='comments',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
