# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('pack_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acquired_date', models.DateTimeField(auto_now_add=True, verbose_name='date acquired')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='acquired_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date acquired'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comments',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='card',
            name='card_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.CardPack'),
        ),
    ]
