# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20160524_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='acquired_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date acquired'),
        ),
        migrations.AlterField(
            model_name='card',
            name='comments',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='cardpack',
            name='acquired_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date acquired'),
        ),
    ]
