# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20160524_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpack',
            name='comments',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='card-photos'),
        ),
    ]
